[2023-06-01T21:15:01.219+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pj_br.DADOS_DEV.extract_data manual__2023-06-01T21:14:58.990958+00:00 [queued]>
[2023-06-01T21:15:01.247+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pj_br.DADOS_DEV.extract_data manual__2023-06-01T21:14:58.990958+00:00 [queued]>
[2023-06-01T21:15:01.247+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-01T21:15:01.247+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-01T21:15:01.247+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-01T21:15:01.278+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): DADOS_DEV.extract_data> on 2023-06-01 21:14:58.990958+00:00
[2023-06-01T21:15:01.289+0000] {standard_task_runner.py:55} INFO - Started process 7413 to run task
[2023-06-01T21:15:01.293+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_pj_br', 'DADOS_DEV.extract_data', 'manual__2023-06-01T21:14:58.990958+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/pip_example.py', '--cfg-path', '/tmp/tmpdjy3yxun']
[2023-06-01T21:15:01.295+0000] {standard_task_runner.py:83} INFO - Job 88: Subtask DADOS_DEV.extract_data
[2023-06-01T21:15:01.388+0000] {task_command.py:389} INFO - Running <TaskInstance: etl_pj_br.DADOS_DEV.extract_data manual__2023-06-01T21:14:58.990958+00:00 [running]> on host e77927a9666c
[2023-06-01T21:15:01.526+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_pj_br
AIRFLOW_CTX_TASK_ID=DADOS_DEV.extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-01T21:14:58.990958+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-01T21:14:58.990958+00:00
[2023-06-01T21:15:01.527+0000] {logging_mixin.py:137} INFO - Reading file...
[2023-06-01T21:15:01.527+0000] {logging_mixin.py:137} INFO - DADOS_DEV
[2023-06-01T21:15:01.546+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pip_example.py", line 26, in extract
    kwargs['ti'].xcom_push(key='raw_data', value=iter(df))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'map' object has no attribute '__module__'
[2023-06-01T21:15:01.560+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=etl_pj_br, task_id=DADOS_DEV.extract_data, execution_date=20230601T211458, start_date=20230601T211501, end_date=20230601T211501
[2023-06-01T21:15:01.577+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 88 for task DADOS_DEV.extract_data ('map' object has no attribute '__module__'; 7413)
[2023-06-01T21:15:01.625+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-01T21:15:01.665+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
